export const projects = [
{
    title: 'Site Art',
    description:"Une landing page sur le thème de l'art pouvant s'adapter aux téléphones mobiles. Entièrement réaliser en pur HTML et CSS.",
    image: '/images/1.png',
    tags: ['HTML', 'CSS'],
    source: 'https://github.com/StevenLignereux/site_art',
    visit: 'https://stevenlignereux.github.io/site_art/',
    id: 0,
  },
  {
    title: 'Page de blog bootstrap',
    description: "Une page de blog créée avec le framework css bootstrap. Le but était de travailler l'utilisation de ce framework.",
      image: '/images/2.png',
      tags: ['HTML', 'Bootstrap', 'CSS'],
    source: 'https://github.com/StevenLignereux/blog_bootstrap',
    visit: 'https://stevenlignereux.github.io/blog_bootstrap/',
    id: 1,
  },
  {
    title: 'Un Site permaculture',
    description: "Page complète sur la permaculture utilisant le framework bootstrap ainsi que HTML, CSS et JS. Le but étant de continuer à développer les compétences dans ces langages et s'intréresser au SEO avec une page plus complète que la précédente.",
    image: '/images/3.png',
    tags: ['HTML', 'CSS', 'JavaScript', 'Bootstrap'],
    source: 'https://github.com/StevenLignereux/permaculture',
    visit: 'https://stevenlignereux.github.io/permaculture/',
    id: 2,
  },
  {
    title: 'Space Travel X',
    description: "Page d'accueil réalisé en HTML SCSS et Javascript. Le but étant d'apprendre le langage SCSS et de travailler des animations sur un thème que j'apprécie particulièrement.",
    image: '/images/4.png',
    tags: ['HTML', 'CSS', 'JavaScript', 'SCSS'],
    source: 'https://github.com/StevenLignereux/spaceTravel',
    visit: 'https://stevenlignereux.github.io/spaceTravel/',
    id: 3,
  },
  {
    title: 'Todo List',
    description: "Une ToDo list réalisée en PHP8. Le but étant de s'entrainer aux nouvelles fonctionnalités du langage PHP. Le langage javascript est aussi utilisé pour des appels asynchrones. La base de donnée est en sqlite afin d'obtenir une application légère.",
    image: '/images/5.png',
    tags: ['HTML', 'CSS', 'JavaScript', 'PHP', 'SQLite'],
    source: 'https://github.com/StevenLignereux/todoList',
    visit: 'http://todolist.stevenlignereux.fr/',
    id: 4,
  },
  {
    title: 'Site du klak',
    description: "Un site créé pour l'association lorientaise le Klak. Le site est un blog avec un système d'administration pour faire connaître l'association. Il utilise le framework php laravel ainsi que du javascript du CSS et d'autres composants du framework comme laravel file manager ou breeze.",
    image: '/images/6.png',
    tags: ['Laravel', 'CSS', 'JavaScript', 'PHP', 'SQLite'],
    // source: 'https://github.com/StevenLignereux/todoList',
    visit: 'https://leklak.fr/',
    id: 5,
  },
  {
    title: 'Développeur web junior',
    description: "Contribution au jobboard développeur web junior, dont le but est de regrouper les offres ne demandant pas d'experience afin de mettre en relation des entreprises ayant besoins de développeurs avec des profils juniors. Travail d'équipe sous la direction de Nicolas Ruiz, avec Edmond de Tournadre et Gaëlle PIERLOT.",
    image: '/images/7.png',
    tags: ['Laravel', 'CSS', 'JavaScript', 'PHP'],
    visit: 'https://developpeurwebjunior.fr/',
    id: 6,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Formation wordpress', },
  { year: 2019, text: 'Stage de développeur symfony', },
  { year: 2020, text: 'Stage développeur FullStack', },
  { year: 2021, text: 'Titre professionnel développeur web et web mobile', },
];
